### ISSUE TITLE
Property '$container' does not exist on type

### ISSUE THREAD

**Issue by jmurdick** [MisterGoodcat/good-injector-vue#1]
I set everything following the instructions here: https://www.npmjs.com/package/good-injector-vue

When I go into my component, I try to access it with this.$container.resolve() but I get the message that "Property '$container' does not exist on type".

Is there a missing dependency?  My index.ts looks like:

```
import { Container, GoodInjectorPlugin } from 'good-injector-vue';

var container = new Container();
IoCContainer.registerService(container);

Vue.use(GoodInjectorPlugin, { container });
```

I put the code use into a mixin like this:

```
import Vue from 'vue';
import { Mixin } from 'vue-mixin-decorator';

import { InjectArguments } from "good-injector-vue";
import { UserService } from '@src/services/UserServices'
import { StudyService } from '@src/services/StudyServices';

@Mixin
export default class ServiceMixin extends Vue {
    private m_userService?: UserService;
    get UserService() { 
        if (this.m_userService != null)
            return this.m_userService;
        throw new Error("UserService not found"); 
    }
    
    private m_studyService?: StudyService;
    get StudyService() {
        if (this.m_studyService != null)
            return this.m_studyService;
        throw new Error("StudyService not found");          
    }

    @InjectArguments()
    public created(userService: UserService, studyService: StudyService) {
        this.m_userService = userService;
        this.m_studyService = studyService;
    }
}
```

Btw, the rest of it works great!  The services are injected just fine, but fortunately the error with $container didn't stop me.

**Comment by MisterGoodcat** [comment]
Hi, thanks for catching this. The plugin does not declare the property for the TypeScript compiler, meaning: $container is there and would be available at runtime, but the compiler does not know about this and complains at compile-time.

You can fix this by adding the declaration in your code (really anywhere):

```ts
declare module "vue/types/vue" {
    interface Vue {
        readonly $container: Container;
    }
}
```

I think this can be added to the plug-in itself, I'll try that later.

**Comment by jmurdick** [comment]
Perfect!  I just put that at the bottom of my index.ts and it works great.  Appreciate the quick response!

**Comment by MisterGoodcat** [comment]
I've published a new version that contains the fix and also updates some dependencies. I did some quick tests in an application of mine - seems to work fine. You should be able to remove the declaration with that new version (please note that i.e. VS Code takes a while to pick up the declaration in the module after updating the package - restarting it helps).
